services:
  mario-client:
    build:
      context: ./mario-client

  mario-server:
    build:
      context: ./mario-server
    ports:
      - 5600:5600

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./mario-client:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mario-client
