networks:
  mario-network:

volumes:
  mario-client-app:

services:
  mario-client:
    image: williamiia/mario-client:latest
    networks:
      - mario-network
    volumes:
      - mario-client-app:/app

  mario-server:
    image: williamiia/mario-server:latest
    networks:
      - mario-network
    ports:
      - 5600:5600

  nginx:
    image: nginx:latest
    networks:
      - mario-network
    ports:
      - 80:80
    volumes:
      - mario-client-app:/usr/share/nginx/html
    depends_on:
      - mario-client