name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: williamiia
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push mario-client image
      uses: docker/build-push-action@v2
      with:
        context: ./mario-client
        file: ./mario-client/Dockerfile
        push: true
        tags: williamiia/mario-client:latest

    - name: Build and push mario-server image
      uses: docker/build-push-action@v2
      with:
        context: ./mario-server
        file: ./mario-server/Dockerfile
        push: true
        tags: williamiia/mario-server:latest
